#!/bin/bash

option=$1
mode=$2

help() {
  echo "Syntax: ideapad-perf [OPTION] MODE"
  echo
  echo "Options:"
  echo " -h, --help                   see this help message"
  echo " -b, --battery-mode           set battery mode"
  echo " -c, -vb, --verify-battery    check (verify) battery mode"
  echo
  echo "Valid battery modes:"
  echo " rc, rapid              Enable Rapid Charge (with Battery Conservation disabled)"
  echo " bc, conserve           Enable Battery Conservation (with Rapid Charge disabled)"
  echo " off                    Disable both Rapid Charge and Battery Conservation"
}

check_acpi() {
  if [[ -z "$(lsmod | grep 'acpi_call')" ]];
    then
    echo 'Module "acpi_call" not loaded, quitting.'
    exit 1
  fi  
}      

convert() {
  case "$1" in
    "0x0")
      echo "off"
      ;;
    "0x1")
      echo "on"
      ;;
    esac
}

verify_battery() {
    check_acpi
    echo '\_SB.PCI0.LPC0.EC0.FCGM' > /proc/acpi/call
    rccheck=$(cat /proc/acpi/call | cut -d '' -f1)
    echo '\_SB.PCI0.LPC0.EC0.BTSG' > /proc/acpi/call
    bccheck=$(cat /proc/acpi/call | cut -d '' -f1)
    echo "Rapid Charge mode is "$(convert $rccheck)", Battery Conservation mode is "$(convert $bccheck)"."
}

case "$option" in
  "" | "-h" | "--help")
    help
    ;;
    
  "-b" | "--battery-mode")
    check_acpi
    case "$mode" in
      "rc" | "rapid")
        echo "Setting battery mode to Rapid Charge (with Battery Conservation disabled)..."
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x05' > /proc/acpi/call
        sleep 1
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x07' > /proc/acpi/call
        verify_battery
        ;;
        
      "bc" | "conserve")
        echo "Setting battery mode to Battery Conservation (with Rapid Charge disabled)..."
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' > /proc/acpi/call
        sleep 1
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x03' > /proc/acpi/call
        verify_battery
        ;;
        
      "off")
        echo "Disabling both Battery Conservation and Rapid Charge mode..."
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' > /proc/acpi/call
        sleep 1
        echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x05' > /proc/acpi/call
        verify_battery
        ;;
        
       "" | *)
        echo "Invalid battery mode."
        verify_battery
        ;;
      esac
    ;;
    
  "-c" | "-vb" | "--verify-battery")
    verify_battery
    ;;
    
   "" | *)
    echo "Invalid option."
    ;;
esac
